ERROR   2022-08-11 10:05:12,917D:\test_msg\api_ui_test\logs\error-2022-08-11-10.log:run.py:28 [WinError 123] 文件名、目录名或卷标语法不正确。: 'D:\\test_msg\\api_ui_test\\ignore:Module already imported:pytest.PytestWarning'
ERROR   2022-08-11 10:06:53,453D:\test_msg\api_ui_test\logs\error-2022-08-11-10.log:run.py:29 'MarkGenerator' object is not callable
ERROR   2022-08-11 10:13:06,999D:\test_msg\api_ui_test\logs\error-2022-08-11-10.log:run.py:29 'MarkGenerator' object is not callable
